### ISSUE TITLE
Code style is inconsistent

### ISSUE THREAD

**Issue by dallashall** [dallashall/react-redux-generator#11]
Ideally, we choose and follow a ready-to-go style-guide. My preference is [AirBnB's JS Styleguide](https://github.com/airbnb/javascript), but I am open to suggestions.

We should probably nip this in the bud while the codebase is small. @dobrynin, this sounds like something you're passionate about?

**Comment by dobrynin** [comment]
I am indeed impassioned by this. I'm all for adopting the AirBnB guide.

**Comment by dallashall** [comment]
AirBnB it is!
