### ISSUE TITLE
Create Example App to Test Templates

### ISSUE THREAD

**Issue by dallashall** [dallashall/react-redux-generator#12]
Rails would probably be the quickest to implement.

**Comment by dallashall** [comment]
For now, I've made a [new branch](https://github.com/dallashall/react-redux-generator/tree/sample-app) for the sample app. It does not have any non-JSON views, WebPack, or React components yet, but the API does work for 'example'.

Will work on getting this react-ready soon, but if someone else wants to take a shot at it before I have a chance, just clone the branch and comment here.

**Comment by dobrynin** [comment]
I'll take a crack at it.

**Comment by dallashall** [comment]
Completed in PR #14.
