### ISSUE TITLE
Template File for Reducer

### ISSUE THREAD

**Issue by dallashall** [dallashall/react-redux-generator#2]
Should work with [thunk-actions](https://github.com/dallashall/react-redux-generator/blob/master/docs/example-templates/example_actions.js). For now, we can be opinionated in how we assume data will come down from the backend.

I'm thinking something like this for grouped data:
```javascript
{
  1: {
      id: 1,
      otherData: data
  },
  3: {
      id: 3,
      otherData: data
  }
}
```
...and something like this for single data:
```javascript
{
  id: 1,
  otherData: data
}
```

**Comment by niartenyaw** [comment]
Definitely like this setup for state org. Do we want to put errors in each separate slice or a single slice for errors at the top level? The latter is simpler but the former gives the ability to render particluar errors in different places.

**Comment by dallashall** [comment]
I think having errors in each separate slice will make the code more modular and flexible. Plus, these templates will make the pain of setting up receiving errors relatively trivial. We'll need to update the actions to handle errors.
